delivery/core/urls.py
from django.contrib import admin
from django.conf.urls.static import static
from django.urls import path, include
from django.conf import settings

js_info_dict = {
    'domain': 'djangojs',
    'packages': ('messages',),
}

urlpatterns = [
    path('admin/', admin.site.urls),
    path('user/', include('user.urls')),
    path('menu/', include('menu.urls')),
    path('order/', include('order.urls')),

] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

delivery/menu/urls.py
from django.urls import path
from menu.delivery.http.handler import getAll, getById, getTodayMenu
from menu.delivery.http.handler import addMenu, deleteMenu, updateMenu
from menu.delivery.http.handler import broadcast_whatsapp_menu

urlpatterns = [
    path('', getAll),
    path('<str:menuId>', getById),
    path('today/', getTodayMenu),
    path('add/', addMenu),
    path('broadcast-whatsapp-menu/', broadcast_whatsapp_menu),
    path('delete/<str:menuId>', deleteMenu),
    path('update/<str:menuId>', updateMenu),
]

delivery/order/urls.py
from django.urls import path
from order.delivery.http.handler import getAll, getById, getAllById
from order.delivery.http.handler import placeOrder

urlpatterns = [
    path('', getAll),
    path('view/<str:orderId>', getById),
    path('all/', getAllById),
    path('create/<str:menuId>', placeOrder),

]

delivery/user/urls.py
from django.urls import path
from user.delivery.http.handler import getAll, getById
from user.delivery.http.handler import authentication, logout
from user.delivery.http.handler import create

urlpatterns = [
    path('', getAll),
    path('<str:userId>', getById),
    path('login/', authentication),
    path('create/', create),
    path('logout/', logout),
]

delivery/menu/models.py
import uuid as uuid
from django.db import models


class Menu(models.Model):
    uuid = models.UUIDField(default=uuid.uuid4, editable=False, unique=True)
    name = models.CharField(max_length=50, null=True)
    description = models.CharField(max_length=250, null=True)
    expiration_date = models.DateTimeField()
    created_date = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.name

delivery/order/models.py
from django.db import models
from menu.models import Menu
from user.models import User


STATUS_CHOICES = (
    ("1", "Pending"),
    ("2", "Prepearing"),
    ("3", "Delivering"),
    ("4", "Delivered"),
)


class Order(models.Model):
    menu = models.ForeignKey(Menu, on_delete=models.DO_NOTHING)
    user = models.ForeignKey(User, on_delete=models.DO_NOTHING)
    customization = models.CharField(max_length=250, null=True)
    created_date = models.DateTimeField(auto_now_add=True)
    delivered_date = models.DateTimeField(auto_now_add=False)
    status = models.CharField(
        max_length=20, choices=STATUS_CHOICES, default='1')

    def __str__(self):
        return self.menu.name

delivery/user/models.py
from django.db import models


class User(models.Model):
    name = models.CharField(max_length=50, null=True)
    phone = models.CharField(max_length=20, null=True)
    admin = models.BooleanField(default=False)
    email = models.CharField(max_length=100, null=False)
    password = models.CharField(max_length=40, null=False)

    def __str__(self):
        return self.name

delivery/menu/forms.py
from django.forms import ModelForm
from menu.models import Menu


class MenuAddForm(ModelForm):
    class Meta:
        model = Menu
        fields = ["name", "description", "expiration_date"]

delivery/order/forms.py
from django.forms import ModelForm
from order.models import Order


class OrderCreateForm(ModelForm):
    class Meta:
        model = Order
        fields = ["customization"]

delivery/user/forms.py
from django.forms import ModelForm
from user.models import User


class AuthForm(ModelForm):
    class Meta:
        model = User
        fields = ["email", "password"]


class CreateForm(ModelForm):
    class Meta:
        model = User
        fields = ["name", "phone", "email", "password"]

delivery/menu/templates/menu_new.html
{% load static %}

<!DOCTYPE html>
<html>
<head>
    <title>Form Menu</title>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/tailwindcss/2.0.1/tailwind.min.css">
    <link rel="stylesheet" type="text/css" href="/static/build/jquery.datetimepicker.min.css"/ >
</head>

<body>
<div class="container mx-auto mt-10">
    <div class="bg-white shadow overflow-hidden sm:rounded-lg">
        <div class="px-4 py-5 sm:px-6">
            <h3 class="text-lg leading-6 font-medium text-gray-900">
                Form Menu
            </h3>
            <p class="mt-1 max-w-2xl text-sm text-gray-500">
                Please fill the form fields with your desired information.
            </p>

            <div>
                {% if saved %}
                <div class="rounded p-3 mt-5 mb-5 bg-green-500 text-white text-center">Your order has been created!
                </div>
                {% endif %}

                {% if saved == False %}
                <div class="rounded p-3 mt-5 mb-5 bg-red-500 text-white text-center">Woops! your order failed, please
                    try again.
                </div>
                {% endif %}

                {% if form.errors %}
                    {% for field in form %}
                    {% for error in field.errors %}
                    <div class="rounded p-3 mt-5 mb-5 bg-red-500 text-white text-center">
                        <strong>{{ error|escape }}</strong>
                    </div>
                    {% endfor %}
                    {% endfor %}
                    {% for error in form.non_field_errors %}
                    <div class="rounded p-3 mt-5 mb-5 bg-red-500 text-white text-center">
                        <strong>{{ error|escape }}</strong>
                    </div>
                    {% endfor %}
                {% endif %}
            </div>
        </div>
        <form method="post" action="/menu/add/" id="menu_form">
            {% csrf_token %}
            <div class="border-t border-gray-200">
                <dl>
                    <div class="bg-gray-50 px-4 py-5 sm:grid sm:grid-cols-3 sm:gap-4 sm:px-6">
                        <dt class="text-sm font-medium text-gray-500">
                            Name
                        </dt>
                        <div class="mt-1 text-sm text-gray-900 sm:mt-0 sm:col-span-2 ">
                            <div class="mt-1 text-sm text-gray-900 sm:mt-0 sm:col-span-2">
{{form.name}}
                            </div>
                        </div>
                    </div>
                    <div class="bg-gray-50 px-4 py-5 sm:grid sm:grid-cols-3 sm:gap-4 sm:px-6">
                        <dt class="text-sm font-medium text-gray-500">
                            Description
                        </dt>
                        <div class="mt-1 text-sm text-gray-900 sm:mt-0 sm:col-span-2">
                            {{form.description}}
                        </div>
                    </div>

                    <div class="bg-gray-50 px-4 py-5 sm:grid sm:grid-cols-3 sm:gap-4 sm:px-6">
                        <dt class="text-sm font-medium text-gray-500">
                            Expiration Date
                        </dt>
                        <div class="mt-1 text-sm text-gray-900 sm:mt-0 sm:col-span-2">
                            {{form.expiration_date}}
                        </div>
                    </div>
                    <div class="bg-white px-4 py-5 sm:grid sm:grid-cols-3 sm:gap-4 sm:px-6">
                        <dt class="text-sm font-medium text-gray-500">
                        </dt>
                        <div class="mt-1 text-sm text-gray-900 sm:mt-0 sm:col-span-2">
                            <button type="submit"
                                    class="rounded-md border ml-0 bg-black p-3 pt-2 pb-2 text-white text-sm m-1">
                                Save
                            </button>
                            <a href="/menu/"
                               class="rounded-md border ml-0 gray p-3 pt-2 pb-2 text-black text-sm m-1">
                                Cancel
                            </a>
                        </div>
                    </div>

                </dl>
            </div>
        </form>
    </div>
</div>
<script src="/static/jquery.js"></script>
<script src="/static/build/jquery.datetimepicker.full.min.js"/></script>
<script>
    jQuery('#id_expiration_date').datetimepicker({
        format: 'd/m/Y H:i',
    });
</script>
</body>
</html>

delivery/menu/templates/menu_today_list.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
    <title>Today's menu</title>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/tailwindcss/2.0.1/tailwind.min.css">
</head>

<body>
<div class="container mx-auto">
    {% if menu_list %}
    <img class="mx-auto h-12 w-auto mt-10" src="{% static '/logo.png' %}" alt="Workflow">
    <div class="uppercase font-bold mt-10">Today's Menu</div>
    {% for menu in menu_list %}

    <div class="p-2 mt-5 border pt-3 pl-3 pr-3 pb-0">
        <div class="flex justify-between">
            <div class="flex flex-col">
                <a class="text-black text-small font-bold pb-1 uppercase" href="/menu/{{ menu.menu_id }}">{{ menu.name }}</a>
                <div class="text-grey-500 pt-1 text-xs mb-5">
                    <div class="mb-5">{{ menu.description}}</div>
                    <div>
                        <a href="/order/create/{{ menu.menu_id }}"
                           class="rounded-md border ml-0 bg-black p-3 pt-2 pb-2 text-white text-sm m-1">
                            Order Now
                        </a>
                    </div>
                </div>
            </div>

            <div class="lowercase font-light text-sm flex flex-row items-center justify-start whitespace-no-wrap">
                <div class="flex flex-row items-center justify-start text-black">
                    <span class="text-grey-500 pt-1 text-xs font-semibold">Expires: {{menu.expire_date}}</span>
                </div>
            </div>
        </div>
    </div>
    {% endfor %}

    {% else %}
    <div class="text-center">No Menus available for today's date.</div>
    {% endif %}
</div>
</body>
</html>

delivery/menu/templates/menu_update.html
{% load static %}

<!DOCTYPE html>
<html>
<head>
    <title>Form Menu</title>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/tailwindcss/2.0.1/tailwind.min.css">
    <link rel="stylesheet" type="text/css" href="/static/build/jquery.datetimepicker.min.css"/ >
</head>

<body>
<div class="container mx-auto mt-10">
    <div class="bg-white shadow overflow-hidden sm:rounded-lg">
        <div class="px-4 py-5 sm:px-6">
            <h3 class="text-lg leading-6 font-medium text-gray-900">
                Form Menu
            </h3>
            <p class="mt-1 max-w-2xl text-sm text-gray-500">
                Please fill the form fields with your desired information.
            </p>

            <div>
                {% if saved %}
                <div class="rounded p-3 mt-5 mb-5 bg-green-500 text-white text-center">Your order has been created!
                </div>
                {% endif %}

                {% if saved == False %}
                <div class="rounded p-3 mt-5 mb-5 bg-red-500 text-white text-center">Woops! your order failed, please
                    try again.
                </div>
                {% endif %}

                {% if form.errors %}
                    {% for field in form %}
                    {% for error in field.errors %}
                    <div class="rounded p-3 mt-5 mb-5 bg-red-500 text-white text-center">
                        <strong>{{ error|escape }}</strong>
                    </div>
                    {% endfor %}
                    {% endfor %}
                    {% for error in form.non_field_errors %}
                    <div class="rounded p-3 mt-5 mb-5 bg-red-500 text-white text-center">
                        <strong>{{ error|escape }}</strong>
                    </div>
                    {% endfor %}
                {% endif %}
            </div>
        </div>
        <form method="post" action="/menu/update/{{ menu.menu_id }}" id="menu_form">
            {% csrf_token %}
            <div class="border-t border-gray-200">
                <dl>
                    <div class="bg-gray-50 px-4 py-5 sm:grid sm:grid-cols-3 sm:gap-4 sm:px-6">
                        <dt class="text-sm font-medium text-gray-500">
                            Name
                        </dt>
                        <div class="mt-1 text-sm text-gray-900 sm:mt-0 sm:col-span-2 ">
                            <div class="mt-1 text-sm text-gray-900 sm:mt-0 sm:col-span-2">
                                <input id="id_name" name="name" type="text" value="{{ menu.name }}" />
                            </div>
                        </div>
                    </div>
                    <div class="bg-gray-50 px-4 py-5 sm:grid sm:grid-cols-3 sm:gap-4 sm:px-6">
                        <dt class="text-sm font-medium text-gray-500">
                            Description
                        </dt>
                        <div class="mt-1 text-sm text-gray-900 sm:mt-0 sm:col-span-2">
                            <input id="id_description" name="description" type="text" value="{{ menu.description }}" />
                        </div>
                    </div>

                    <div class="bg-gray-50 px-4 py-5 sm:grid sm:grid-cols-3 sm:gap-4 sm:px-6">
                        <dt class="text-sm font-medium text-gray-500">
                            Expiration Date
                        </dt>
                        <div class="mt-1 text-sm text-gray-900 sm:mt-0 sm:col-span-2">
                            <input id="id_expiration_date" name="expiration_date" type="text" value="{{ menu.expire_date|date:"d/m/Y H:i" }}" />
                        </div>
                    </div>
                    <div class="bg-white px-4 py-5 sm:grid sm:grid-cols-3 sm:gap-4 sm:px-6">
                        <dt class="text-sm font-medium text-gray-500">
                        </dt>
                        <div class="mt-1 text-sm text-gray-900 sm:mt-0 sm:col-span-2">
                            <button type="submit"
                                    class="rounded-md border ml-0 bg-black p-3 pt-2 pb-2 text-white text-sm m-1">
                                Save
                            </button>
                            <a href="/menu/"
                               class="rounded-md border ml-0 gray p-3 pt-2 pb-2 text-black text-sm m-1">
                                Cancel
                            </a>
                        </div>
                    </div>

                </dl>
            </div>
        </form>
    </div>
</div>
<script src="/static/jquery.js"></script>
<script src="/static/build/jquery.datetimepicker.full.min.js"/></script>
<script>
    jQuery('#id_expiration_date').datetimepicker({
        format: 'd/m/Y H:i',
    });
</script>
</body>
</html>

delivery/menu/templates/menu_view.html
<!DOCTYPE html>
<html>
<head>
    <title>Menu Item</title>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/tailwindcss/2.0.1/tailwind.min.css">
</head>

<body>
<div class="container mx-auto mt-10">
    <div class="bg-white shadow overflow-hidden sm:rounded-lg">
        <div class="px-4 py-5 sm:px-6">
            <h3 class="text-lg leading-6 font-medium text-gray-900">
                Today's Menu
            </h3>
        </div>
        <form method="post" action="/order/create/{{ menu.menu_id }}" id="order_form">
            {% csrf_token %}
            <div class="border-t border-gray-200">
                <div>
                    <div class="bg-gray-50 px-4 py-5 sm:grid sm:grid-cols-3 sm:gap-4 sm:px-6">
                        <dt class="text-sm font-medium text-gray-500">
                            Item
                        </dt>
                        <dd class="mt-1 text-sm text-gray-900 sm:mt-0 sm:col-span-2">
                            {{ menu.name }}
                        </dd>
                    </div>
                    <div class="bg-gray-50 px-4 py-5 sm:grid sm:grid-cols-3 sm:gap-4 sm:px-6">
                        <dt class="text-sm font-medium text-gray-500">
                            Description
                        </dt>
                        <dd class="mt-1 text-sm text-gray-900 sm:mt-0 sm:col-span-2">
                            {{ menu.description }}
                        </dd>
                    </div>

                    <div class="bg-gray-50 px-4 py-5 sm:grid sm:grid-cols-3 sm:gap-4 sm:px-6">
                        <dt class="text-sm font-medium text-gray-500">
                            This meal is available before
                        </dt>
                        <dd class="mt-1 text-sm text-gray-900 sm:mt-0 sm:col-span-2">
                            {{ menu.expire_date }}
                        </dd>
                    </div>

                    <div class="bg-white px-4 py-5 sm:grid sm:grid-cols-3 sm:gap-4 sm:px-6">
                        <dt class="text-sm font-medium text-gray-500">
                        </dt>
                        <dd class="mt-1 text-sm text-gray-900 sm:mt-0 sm:col-span-2">
                            <a href="/order/create/{{ menu.menu_id }}"
                                    class="rounded-md border ml-0 bg-black p-3 pt-2 pb-2 text-white text-sm m-1">
                                Order Now
                            </a>
                            <a href="/menu/today/"
                               class="rounded-md border ml-0 gray p-3 pt-2 pb-2 text-black text-sm m-1">
                                Cancel
                            </a>
                        </dd>
                    </div>

                </div>
            </div>
        </form>
    </div>
</div>
</body>
</html>

delivery/menu/templates/menus.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
    <title>Login</title>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/tailwindcss/2.0.1/tailwind.min.css">
</head>

<body>
<div class="container mx-auto">
    {% if menu_list %}
    <img class="mx-auto h-12 w-auto mt-10" src="{% static '/logo.png' %}" alt="Workflow">
    <div class="uppercase font-bold mt-10">Admin Menu</div>
    {% for menu in menu_list %}

    <div class="p-2 mt-5 border pt-3 pl-3 pr-3 pb-0">
        <div class="flex justify-between">
            <div class="flex flex-col">
                <a class="text-black text-small font-bold pb-1 uppercase" href="/menu/{{ menu.menu_id }}">{{ menu.name }}</a>
                <div class="text-grey-500 pt-1 text-xs mb-5">
                    <div class="mb-5">{{ menu.description}}</div>
                    <div>
                        <a href="/menu/delete/{{ menu.menu_id }}"
                           class="rounded-md border ml-0 bg-red-500 p-3 pt-2 pb-2 text-white text-sm m-1">
                            Delete 
                        </a>

                        <a href="/menu/update/{{ menu.menu_id }}"
                           class="rounded-md border ml-0 bg-black p-3 pt-2 pb-2 text-white text-sm m-1">
                            Modify 
                        </a>
                    </div>
                </div>
            </div>

            <div class="lowercase font-light text-sm flex flex-row items-center justify-start whitespace-no-wrap">
                <div class="flex flex-row items-center justify-start text-black">
                    <span class="text-grey-500 pt-1 text-xs font-semibold">Expires: {{menu.expire_date}}</span>
                </div>
            </div>
        </div>
    </div>
    {% endfor %}

    {% else %}
    <div class="text-center">No Menus available for today's date.</div>
    {% endif %}
</div>
</body>
</html>

delivery/order/templates/order_new.html
<!DOCTYPE html>
<html>
<head>
    <title>New Order</title>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/tailwindcss/2.0.1/tailwind.min.css">
</head>

<body>
<div class="container mx-auto mt-10">
    <div class="bg-white shadow overflow-hidden sm:rounded-lg">
        <div class="px-4 py-5 sm:px-6">
            <h3 class="text-lg leading-6 font-medium text-gray-900">
                Create Menu Order
            </h3>
            <p class="mt-1 max-w-2xl text-sm text-gray-500">
                Please fill the form fields with your desired information.
            </p>

            <div>
                {% if saved %}
                <div class="rounded p-3 mt-5 mb-5 bg-green-500 text-white text-center">Your order has been created!
                </div>
                {% endif %}

                {% if saved == False %}
                <div class="rounded p-3 mt-5 mb-5 bg-red-500 text-white text-center">Woops! your order failed, please
                    try again.
                </div>
                {% endif %}

                {% if form.errors %}
                    {% for field in form %}
                    {% for error in field.errors %}
                    <div class="rounded p-3 mt-5 mb-5 bg-red-500 text-white text-center">
                        <strong>{{ error|escape }}</strong>
                    </div>
                    {% endfor %}
                    {% endfor %}
                    {% for error in form.non_field_errors %}
                    <div class="rounded p-3 mt-5 mb-5 bg-red-500 text-white text-center">
                        <strong>{{ error|escape }}</strong>
                    </div>
                    {% endfor %}
                {% endif %}
            </div>
        </div>
        <form method="post" action="/order/create/{{ menu.menu_id }}" id="order_form">
            {% csrf_token %}
            <div class="border-t border-gray-200">
                <dl>
                    <div class="bg-gray-50 px-4 py-5 sm:grid sm:grid-cols-3 sm:gap-4 sm:px-6">
                        <dt class="text-sm font-medium text-gray-500">
                            Chosen Menu
                        </dt>
                        <dd class="mt-1 text-sm text-gray-900 sm:mt-0 sm:col-span-2">
                            {{ menu.name }}
                        </dd>
                    </div>
                    <div class="bg-gray-50 px-4 py-5 sm:grid sm:grid-cols-3 sm:gap-4 sm:px-6">
                        <dt class="text-sm font-medium text-gray-500">
                            Customization
                        </dt>
                        <dd class="mt-1 text-sm text-gray-900 sm:mt-0 sm:col-span-2">
                            <textarea id="id_customization" name="customization" class="border w-full h-30"
                                      required></textarea>
                            <div>Type here if you don't want anything. (example: Alergic to garlic etc)</div>
                        </dd>
                    </div>
                    <div class="bg-white px-4 py-5 sm:grid sm:grid-cols-3 sm:gap-4 sm:px-6">
                        <dt class="text-sm font-medium text-gray-500">
                        </dt>
                        <dd class="mt-1 text-sm text-gray-900 sm:mt-0 sm:col-span-2">
                            <button type="submit"
                                    class="rounded-md border ml-0 bg-black p-3 pt-2 pb-2 text-white text-sm m-1">
                                Order Now
                            </button>
                            <a href="/menu/today/"
                               class="rounded-md border ml-0 gray p-3 pt-2 pb-2 text-black text-sm m-1">
                                Cancel
                            </a>
                        </dd>
                    </div>

                </dl>
            </div>
        </form>
    </div>
</div>
</body>
</html>

delivery/order/templates/order_view.html
<!DOCTYPE html>
<html>
<head>
    <title>Menu Item</title>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/tailwindcss/2.0.1/tailwind.min.css">
</head>

<body>
<div class="container mx-auto mt-10">
    <div class="bg-white shadow overflow-hidden sm:rounded-lg">
        <div class="px-4 py-5 sm:px-6">
            <h3 class="text-lg leading-6 font-medium text-gray-900">
                Order Number N{{ order.order_id }}
            </h3>
        </div>
        <form method="post" action="/order/create/{{ menu.menu_id }}" id="order_form">
            {% csrf_token %}
            <div class="border-t border-gray-200">
                <div>
                    <div class="bg-gray-50 px-4 py-5 sm:grid sm:grid-cols-3 sm:gap-4 sm:px-6">
                        <dt class="text-sm font-medium text-gray-500">
                            Chosen Menu
                        </dt>
                        <dd class="mt-1 text-sm text-gray-900 sm:mt-0 sm:col-span-2">
                            {{ order.menu.name}}
                        </dd>
                    </div>

                    <div class="bg-gray-50 px-4 py-5 sm:grid sm:grid-cols-3 sm:gap-4 sm:px-6">
                        <dt class="text-sm font-medium text-gray-500">
                            Order date
                        </dt>
                        <dd class="mt-1 text-sm text-gray-900 sm:mt-0 sm:col-span-2">
                            {{ order.created_date }}
                        </dd>
                    </div>

                    <div class="bg-gray-50 px-4 py-5 sm:grid sm:grid-cols-3 sm:gap-4 sm:px-6">
                        <dt class="text-sm font-medium text-gray-500">
                            Customization
                        </dt>
                        <dd class="mt-1 text-sm text-gray-900 sm:mt-0 sm:col-span-2">
                            {{ order.customization}}
                        </dd>
                    </div>

                    <div class="bg-gray-50 px-4 py-5 sm:grid sm:grid-cols-3 sm:gap-4 sm:px-6">
                        <dt class="text-sm font-medium text-gray-500">
                            Order Status
                        </dt>
                        <dd class="mt-1 text-sm text-gray-900 sm:mt-0 sm:col-span-2">
                            Your order is {{ order.status }}
                        </dd>
                    </div>

                    <div class="bg-white px-4 py-5 sm:grid sm:grid-cols-3 sm:gap-4 sm:px-6">
                        <dt class="text-sm font-medium text-gray-500">
                        </dt>
                        <dd class="mt-1 text-sm text-gray-900 sm:mt-0 sm:col-span-2">
                            <a href="/order/all/"
                               class="rounded-md border ml-0 gray p-3 pt-2 pb-2 text-black text-sm m-1">
                                Go Back
                            </a>
                        </dd>
                    </div>

                </div>
            </div>
        </form>
    </div>
</div>
</body>
</html>

delivery/user/templates/user_auth.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
    <title>Login</title>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/tailwindcss/2.0.1/tailwind.min.css">
</head>

<body>
<div class="min-h-screen flex items-center justify-center bg-gray-50 py-12 px-4 sm:px-6 lg:px-8">
    <div class="max-w-md w-full space-y-8">
        <div>
            <img class="mx-auto h-12 w-auto" src="{% static '/logo.png' %}" alt="Workflow">
            <h2 class="mt-6 text-center text-3xl font-extrabold text-gray-900">
                Sign in to your menu account
            </h2>

            {% if error %}
            <div class="text-center mt-5 mb-5">Your email and password didn't match. Please try again.</div>
            {% endif %}

        </div>
        <form class="mt-8 space-y-6" action="/user/login/" method="POST">
            {% csrf_token %}
            <div class="rounded-md shadow-sm -space-y-px">
                <div>
                    <label for="id_email" class="sr-only">Email address</label>
                    <input id="id_email" name="email" type="email" required
                           class="appearance-none rounded-none relative block w-full px-3 py-2 border border-gray-300 placeholder-gray-500 text-gray-900 rounded-t-md focus:outline-none focus:ring-indigo-500 focus:border-indigo-500 focus:z-10 sm:text-sm"
                           placeholder="Email address">
                </div>
                <div>
                    <label for="id_password" class="sr-only">Password</label>
                    <input id="id_password" name="password" type="password" required
                           class="appearance-none rounded-none relative block w-full px-3 py-2 border border-gray-300 placeholder-gray-500 text-gray-900 rounded-b-md focus:outline-none focus:ring-indigo-500 focus:border-indigo-500 focus:z-10 sm:text-sm"
                           placeholder="Password">
                </div>
            </div>


            <div>
                <button type="submit"
                        class="group relative w-full flex justify-center py-2 px-4 border border-transparent text-sm font-medium rounded-md text-white bg-indigo-600 hover:bg-indigo-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-indigo-500">
          <span class="absolute left-0 inset-y-0 flex items-center pl-3">
            <!-- Heroicon name: lock-closed -->
            <svg class="h-5 w-5 text-indigo-500 group-hover:text-indigo-400" xmlns="http://www.w3.org/2000/svg"
                 viewBox="0 0 20 20" fill="currentColor" aria-hidden="true">
              <path fill-rule="evenodd"
                    d="M5 9V7a5 5 0 0110 0v2a2 2 0 012 2v5a2 2 0 01-2 2H5a2 2 0 01-2-2v-5a2 2 0 012-2zm8-2v2H7V7a3 3 0 016 0z"
                    clip-rule="evenodd"/>
            </svg>
          </span>
                    Sign in
                </button>
            </div>
        </form>
    </div>
</div>
</body>
</html>

delivery/user/templates/user_view.html
<h2>{{ user.name}}</h2>
<p>phone: {{ user.phone}}</p>
<p>is user admin: {{ user.admin}}</p>

delivery/user/templates/users.html
{% if user_list %}
<ul>
  {% for user in user_list %}
  <li><a href="/user/{{ user.user_id }}">{{ user.name }}</a></li>
  {% endfor %}
</ul>
{% else %}
<p>No users are available.</p>
{% endif %}